pull_request_rules:
  - name: VM3 Classic default Summary provenance external 260922
    conditions:
      - author = livastic-vm3-secondary-20260911
      - title = VM3 CLASSIC DEFAULT SUMMARY PROVENANCE 260922
    actions:
      merge:
        method: merge
        merge_bot_account: livastic-vm3-primary-tmp-260920
